### ISSUE TITLE
Error inCH5 V3, import failure

### ISSUE THREAD

**Issue by denseuropa** [PacktPublishing/Quantum-Chemistry-and-Computing-for-the-Curious#11]
import pygmc.api as pyq

ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/cupy/__init__.py in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

7 frames
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/cupy/__init__.py in <module>
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
     21 {_environment._diagnose_import_error()}

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by AlainChance** [comment]
Thank you for trying out the companion jupyter notebook V3 for Chapter 5 of the book "Quantum Chemistry and Computing for the Curious: Illustrated with Python and Qiskit® code" by Dr. Keeper L. Sharkey and Alain Chancé, foreword by Alex Khan, Packt Publishing (May 20, 2022).

As shown in the enclosed screenshot, the statement "pip install pyqmc --upgrade" works fine in the jupyter notebook V3 for Chapter 5:
![Import the PyQMC API library successful](https://github.com/user-attachments/assets/a8ce9807-16f9-4d2d-8798-c0d2b1738feb)

Please note, I suggest correcting "**pygmc**" to **"pyqmc**" in your statement "import pygmc.api as pyq". PyQMC is a python module that implements real-space quantum Monte Carlo techniques. Check: https://github.com/WagnerGroup/pyqmc

As mentioned in the top cell 5, "Variational Quantum Eigensolver (VQE) Algorithm, Technical Requirements, and Updates," a "Summary of Updates V3" is provided at the end of the notebook, just after cell 73 (see enclosed screenshot). Please refer to it.

![Summary of Updates V3](https://github.com/user-attachments/assets/a4fe3e97-e9d2-4518-b4c9-992c24185b83)

For Qiskit support, you may join the Qiskit Slack at [qiskit.enterprise.slack.com](https://qiskit.enterprise.slack.com/) and access the channel #qiskit-support.

**Comment by denseuropa** [comment]
Thank you for your response and the q to g typo was in the email, the V3 downloaded notebook was what failed. I have as a scientist been conducting my own research and have tabulated below my findings.

 

PYQMC

Install pip install pyqmc –upgrade

Last release 0.6.0 May 17 2023

Maintainer: Lucas Wagner

Publication: Journal of Chemical Physics, Journal Name: Journal of Chemical Physics Vol.      158 Journal Issue: 11; ISSN 0021-9606

Code: PyQMC runs on CPUs and GPUs using the same code paths. GPU capability is implemented using the CuPy library, <javascript:;> 73 which is used as a drop-in replacement for NumPy

 

CuPy

Description: CuPy is an open-source array library for GPU-accelerated computing with Python. CuPy utilizes CUDA Toolkit libraries

Requirements:

                NVIDIA CUDA GPU <https://developer.nvidia.com/cuda-gpus>  with the Compute Capability 3.0 or larger.

CUDA Toolkit <https://developer.nvidia.com/cuda-toolkit> : v11.2 / v11.3 / v11.4 / v11.5 / v11.6 / v11.7 / v11.8 / v12.0 / v12.1 / v12.2 / v12.3 / v12.4 / v12.5 / v12.6

CUDA Libraries: cuTENSOR <https://developer.nvidia.com/cutensor> : v2.0, NCCL <https://developer.nvidia.com/nccl> : v2.16 / v2.17, cuDNN <https://developer.nvidia.com/cudnn> : v8.8, cuSPARSELt <https://docs.nvidia.com/cuda/cusparselt/> : v0.2.0

Installation: pip install cupy-cuda??x where ??= 11 or 12 also possibly python -m  cupyx.tools.install_library --cuda 11.x --library cutensor

Installation — CuPy 13.3.0 documentation <https://docs.cupy.dev/en/stable/install.html> 

 

As you can see the pyqmc routine relies on CuPy which in turn requires an NVIDIA GPU and specifically the NVIDIA CUDA software. As it happens my desktop PC has an NVIDIA GeForce GTX 650Ti running CUDA 9.0 which isn’t in the CuPy requirements list (too old and may not have the required compute capacity?)  While my laptop  has an NVIDIA GeForce RTX 4070 I haven’t yet installed CUDA and as there is no mention in the book of GPU requirements or software I am unhappy about blindly downloading  possibly the wrong version of the software. Particularly given the difficulty of removing versions of NVIDIA software.

 

One of the things I have noticed with qiskit is the rapid turnover of modules  versions which are often not backwards compatible, I did not find the summary of update helpful( which I had already browsed) helpful with my issue

 

Happy Halloween

 

Dennis

**Comment by AlainChance** [comment]
No GPU is required to successfully run the companion Jupyter notebooks for the book "Quantum Chemistry and Computing for the Curious: Illustrated with Python and Qiskit® code" by Dr. Keeper L. Sharkey and Alain Chancé, foreword by Alex Khan, Packt Publishing (May 20, 2022).

We recommend using [Python virtual environments](https://docs.python.org/3.10/tutorial/venv.html) to isolate Qiskit and the companion Jupyter notebooks of our book from other applications. For guidance, please refer to the [Install Qiskit](https://docs.quantum.ibm.com/guides/install-qiskit#local) section, specifically "Install the Qiskit SDK and the Qiskit Runtime client."

For Qiskit support, you may join the Qiskit Slack at qiskit.enterprise.slack.com <https://qiskit.enterprise.slack.com/>  and access the channel #qiskit-support.

**Comment by denseuropa** [comment]
Hi again

 

I have already discovered Derek Wang’s excellent videos which work perfectly in my systems. I have a google sign in and also an IBM account for access to quantum computers, which both work.

This is a screenshot of my PC running your code, which as far as I understand it is running in the COLAB environment. I may have missed it but where in the text of the book do you a)  recommend using Python virtual environments <https://docs.python.org/3.10/tutorial/venv.html>  to isolate Qiskit or b)  For guidance, please refer to the Install Qiskit <https://docs.quantum.ibm.com/guides/install-qiskit#local>  section, specifically "Install the Qiskit SDK and the Qiskit Runtime client." And anyway how does that solve my problem?

 

Dennis

**Comment by AlainChance** [comment]
For Qiskit support, you may join the Qiskit Slack at qiskit.enterprise.slack.com https://qiskit.enterprise.slack.com/ and access the channel #qiskit-support.

**Comment by denseuropa** [comment]
I have finally sorted this issue, unfortunately none of the interesting suggestions helped. Going back to first principles and the on-line documentation pyQMC relies on CuPy which in turn DOES require a GPU. However the non-premium version of COLAB does not have access to a GPU unless the session specifically requests one. e.g. COLAB/runtime/change runtime type/select T4 GPU. Chapter_05 now works for me. It has to be said the original error message would have been more helpful if it had just pointed out the absence of a GPU.

**Comment by AlainChance** [comment]
It’s great to hear that the companion Jupyter notebook V3 for Chapter 5 now works for you.

[pyQMC](https://github.com/WagnerGroup/pyqmc) (Python Quantum Monte Carlo) requires only SciPy, pandas, PySCF, and h5py as shown in the following files:

[pyqmc/requirements.txt ](https://github.com/WagnerGroup/pyqmc/blob/master/requirements.txt)

![requirements txt](https://github.com/user-attachments/assets/79fd3b03-dc53-4ae0-a347-0b626419225e)

[pyqmc/setup.py](https://github.com/WagnerGroup/pyqmc/blob/master/setup.py) function setup_pyqmc()

install_requires=[
            "scipy",
            "pandas",
            "pyscf",
            "h5py"
        ],

![setup_pyqmc](https://github.com/user-attachments/assets/986e5a98-ad68-42eb-b220-eeeeeb3ec4b5)

No GPU is required to successfully run the companion Jupyter notebooks for the book _Quantum Chemistry and Computing for the Curious: Illustrated with Python and Qiskit® code_ by Dr. Keeper L. Sharkey and Alain Chancé, foreword by Alex Khan, Packt Publishing (May 20, 2022).

For Qiskit support, you may join the Qiskit Slack at [qiskit.enterprise.slack.com](https://qiskit.enterprise.slack.com/) and access the channel #qiskit-support.

**Comment by denseuropa** [comment]
1. To confirm all tests have been done with the spelling import pyqmc.api as pyq.

 

2. On startup: colab/Runtime/view resources has system Ram and Disk NO GPU

Running Chap5 code up to the line import pyqmc.api as pyq produces the error first reported

 

3. Changing runtime type: colab\runtime\T4 GPU, resources now show System RAM, GPU RAM and disk

Running Chap5 code up to the line import pyqmc.api as pyq runs successfully

 

4. Changing runtime type to no GPU: colab\runtime\CPU, resources now show System RAM and disk

Running Chap5 code up to the line import pyqmc.api as pyq produces the error first reported

 

5. Changing runtime type: colab\runtime\T4 GPU resources, now show System RAM, GPU RAM and disk

Running Chap5 code up to the line import pyqmc.api as pyq runs successfully

 

This sequence occurs on a windows 10 desktop, a windows 11 laptop, both running EDGE and a Linux laptop running UBUNTU 22.04 and Firefox

 

Points on note

a) COLAB appears to start up with the resources last used

b) As a practical scientist I tend to prefer actual experiments to theoretical interpretation of code, particularly with unknown software dependencies

c) With regards to CuPy the 4th line of the original error message is reproduced below indicating some involvement:

 

ImportError                               Traceback (most recent call last)

/usr/local/lib/python3.10/dist-packages/cupy/__init__.py in <module>

     16 try:

---> 17     from cupy import _core  # NOQA

 

I can't afford to waste any more time on this particularly as I have reported to PACKT the ridiculous variation in font size in my version makes the text impossible to follow.
